### ISSUE TITLE
Error on golang 1.12 on windows.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen_GO#15]
When launch on windows about 50% of the time it crashes at startup.
Here is the error log:
http://www.mediafire.com/file/4ba4b8cj6qu7lp1/Error+log+Windows+Golang+1.12.txt
This behaviour is not present on GOlang 1.11.
And only happens on the windows platform.

We need more info on what causes it.

**Comment by Windblade-GR01** [comment]
Here is the error log without the need to download it.
```
Exception 0xc0000005 0x0 0xc0011c0000 0x7ffc0ea8e8c9
PC=0x7ffc0ea8e8c9
signal arrived during external code execution

github.com/go-gl/gl/v2.1/gl._Cfunc_glowTexImage2D(0x7ffc3d4ddf80, 0xde1, 0x14000001909, 0x80, 0x140100001909, 0xc0011b9800)
        _cgo_gotypes.go:40585 +0x4c
github.com/go-gl/gl/v2.1/gl.TexImage2D.func1(0xde1, 0x14000001909, 0x80, 0x140100001909, 0xc0011b9800)
        /code/go/src/github.com/go-gl/gl/v2.1/gl/package.go:26077 +0xb7
github.com/go-gl/gl/v2.1/gl.TexImage2D(0xde1, 0x14000001909, 0x80, 0x140100001909, 0xc0011b9800)
        /code/go/src/github.com/go-gl/gl/v2.1/gl/package.go:26077 +0x72
main.(*Sprite).SetPxl.func1()
        /code/src/image.go:536 +0x109
main.(*System).runMainThreadTask(0x7dfd20)
        /code/src/system.go:326 +0x30
main.(*System).await(0x7dfd20, 0x3c, 0x0)
        /code/src/system.go:340 +0x40
main.(*System).update(0x7dfd20, 0x3fe74699ace4cff9)
        /code/src/system.go:380 +0x8f
main.systemScriptInit.func45(0xc000060320, 0x1)
        /code/src/script.go:652 +0x51
github.com/yuin/gopher-lua.callGFunction(0xc000060320, 0x0, 0xc00137e101)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:136 +0x47
github.com/yuin/gopher-lua.init.3.func26(0xc000060320, 0x7c040201, 0xc0001e60a0, 0x0)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:717 +0x383
github.com/yuin/gopher-lua.mainLoop(0xc000060320, 0xc0001e60a0)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:31 +0xe3
github.com/yuin/gopher-lua.(*LState).callR(0xc000060320, 0x1, 0x1, 0xa)
        /code/go/src/github.com/yuin/gopher-lua/state.go:876 +0x24d
github.com/yuin/gopher-lua.(*LState).Call(...)
        /code/go/src/github.com/yuin/gopher-lua/state.go:1613
github.com/yuin/gopher-lua.loRequire(0xc000060320, 0x10)
        /code/go/src/github.com/yuin/gopher-lua/baselib.go:559 +0x636
github.com/yuin/gopher-lua.callGFunction(0xc000060320, 0x0, 0x1)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:136 +0x47
github.com/yuin/gopher-lua.init.3.func26(0xc000060320, 0x7c1c0402, 0xc0001e6000, 0x0)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:717 +0x383
github.com/yuin/gopher-lua.mainLoop(0xc000060320, 0xc0001e6000)
        /code/go/src/github.com/yuin/gopher-lua/vm.go:31 +0xe3
github.com/yuin/gopher-lua.(*LState).callR(0xc000060320, 0x0, 0xffffffffffffffff, 0x0)
        /code/go/src/github.com/yuin/gopher-lua/state.go:876 +0x24d
github.com/yuin/gopher-lua.(*LState).Call(...)
        /code/go/src/github.com/yuin/gopher-lua/state.go:1613
github.com/yuin/gopher-lua.(*LState).PCall(0xc000060320, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /code/go/src/github.com/yuin/gopher-lua/state.go:1676 +0xed
github.com/yuin/gopher-lua.(*LState).DoFile(0xc000060320, 0xc000066c00, 0xf, 0xc000186000, 0x60)
        /code/go/src/github.com/yuin/gopher-lua/auxlib.go:394 +0xcb
main.main()
        /code/src/main.go:239 +0x14d9

goroutine 19 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go-1.12/src/runtime/proc.go:307
time.Sleep(0x989680)
        /usr/lib/go-1.12/src/runtime/time.go:105 +0x16e
main.(*System).soundWrite(0x7dfd20)
        /code/src/system.go:409 +0x42c
created by main.(*System).audioOpen
        /code/src/system.go:393 +0xdd

goroutine 20 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go-1.12/src/runtime/proc.go:307
time.Sleep(0xbebc20)
        /usr/lib/go-1.12/src/runtime/time.go:105 +0x16e
github.com/hajimehoshi/oto.(*driverWriter).Write(0xc00005cba0, 0xc0001c6070, 0x90, 0x7f90, 0x0, 0x0, 0x0)
        /code/go/src/github.com/hajimehoshi/oto/context.go:152 +0x1b9
io.copyBuffer(0x9a4e40, 0xc00005cba0, 0x9a4e80, 0xc0000623c0, 0xc0001c6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.12/src/io/io.go:404 +0x202
io.Copy(...)
        /usr/lib/go-1.12/src/io/io.go:364
github.com/hajimehoshi/oto.NewContext.func1(0xc00005cbc0)
        /code/go/src/github.com/hajimehoshi/oto/context.go:85 +0x71
created by github.com/hajimehoshi/oto.NewContext
        /code/go/src/github.com/hajimehoshi/oto/context.go:84 +0x230

goroutine 21 [select]:
io.(*pipe).Write(0xc0000ac140, 0xc0001ac090, 0x4458, 0x4458, 0x90, 0x0, 0x0)
        /usr/lib/go-1.12/src/io/pipe.go:87 +0x1d0
io.(*PipeWriter).Write(0xc00008c1b0, 0xc0001ac000, 0x44e8, 0x44e8, 0x113a, 0x1, 0x0)
        /usr/lib/go-1.12/src/io/pipe.go:153 +0x53
github.com/hajimehoshi/oto.(*Player).Write(...)
        /code/go/src/github.com/hajimehoshi/oto/player.go:60
github.com/faiface/beep/speaker.update()
        /code/go/src/github.com/faiface/beep/speaker/speaker.go:117 +0x197
github.com/faiface/beep/speaker.Init.func1()
        /code/go/src/github.com/faiface/beep/speaker/speaker.go:56 +0x2b
created by github.com/faiface/beep/speaker.Init
        /code/go/src/github.com/faiface/beep/speaker/speaker.go:52 +0x1eb

goroutine 22 [syscall, locked to thread]:
syscall.Syscall6(0x7ffc67722b10, 0x5, 0x54, 0xc000254000, 0x1000, 0xc00000a048, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go-1.12/src/runtime/syscall_windows.go:199 +0xed
syscall.ReadConsole(0x54, 0xc000254000, 0x1000, 0xc00000a048, 0x0, 0xc0001c5cb0, 0x0)
        /usr/lib/go-1.12/src/syscall/zsyscall_windows.go:1309 +0xb6
internal/poll.(*FD).readConsole(0xc00008ec80, 0xc00020d000, 0x1000, 0x1000, 0x100000000000000, 0x0, 0x1000)
        /usr/lib/go-1.12/src/internal/poll/fd_windows.go:539 +0x250
internal/poll.(*FD).Read(0xc00008ec80, 0xc00020d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.12/src/internal/poll/fd_windows.go:492 +0x13a
os.(*File).read(...)
        /usr/lib/go-1.12/src/os/file_windows.go:207
os.(*File).Read(0xc00008c080, 0xc00020d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go-1.12/src/os/file.go:108 +0x77
bufio.(*Scanner).Scan(0xc0001c5f48, 0x0)
        /usr/lib/go-1.12/src/bufio/scan.go:213 +0xab
main.(*System).init.func1(0x7dfd20)
        /code/src/system.go:293 +0x10e
created by main.(*System).init
        /code/src/system.go:291 +0x41e
rax     0x6a00
rbx     0x140
rcx     0xfffffe00
rdi     0x3f
rsi     0xfffffe0e
rbp     0x1aff300
rsp     0x1aff200
r8      0xa880900
r9      0xfffffe08
r10     0xc0011bfd40
r11     0xfffffe0c
r12     0xa87a100
r13     0x3f
r14     0xc0011bfc40
r15     0x1aff430
rip     0x7ffc0ea8e8c9
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by Windblade-GR01** [comment]
Well I found the problem.
Is the garage collector deleting data before it could load the data.
If you disable it it will never crash.

According to golang 1.12 patch notes.
```
Go 1.12 significantly improves the performance of sweeping when a large fraction of the heap
remains live. This reduces allocation latency immediately following a garbage collection.

The Go runtime now releases memory back to the operating system more aggressively,
particularly in response to large allocations that can't reuse existing heap space.

The Go runtime's timer and deadline code is faster and scales better with higher numbers of CPUs.
In particular, this improves the performance of manipulating network connection deadlines.
```
So a large allocation happens in the boot time so the GC goes on a rampage deleting the stuff that needs to be parsed to openGL.

GO garbage collector is incredibly fast it takes microseconds others languages GC take milliseconds. So we can't be faster than the GC, the only way I can think is reduce manually the GC rate at the load screens (And only at load screens we can restore the GC rate at other parts)
So well I will find a way to reduce the aggressiveness of the GC at boot time so it does not crash anymore.

**Comment by Windblade-GR01** [comment]
Fixed in this commit.
https://github.com/Windblade-GR01/Ikemen_GO/commit/0607bdc789f0ea0405aa9f9f2ac1bdb8f2d9b9bb

I made a bidding to GO's SetGCPercent.
It disables the GC on the initial load.
Once it loads it restores it to normal.
